repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix, --select=I]
        files: ^.*\.ipynb$
      - id: ruff-format
        files: ^.*\.ipynb$
