project:
  type: website
  pre-render: bash _extras/social_cards/prerender.sh
  resources:
    - CNAME
    - fonts/

website:
  title: Dylan Castillo
  site-url: https://dylancastillo.co
  image: /images/social_media_card.png
  favicon: images/logo.webp
  open-graph: true
  twitter-card:
    site: "@dylanjcastillo"
    creator: "@dylanjcastillo"
  navbar:
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "{{< iconify fa6-brands github >}}"
        href: https://github.com/dylanjcastillo
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: https://www.linkedin.com/in/dylanjcastillo/
      - text: "{{< iconify fa6-solid rss >}}"
        href: index.xml
  page-footer:
    left: "© Dylan Castillo"
    right:
      - text: "Newsletter"
        href: https://subscribe.dylancastillo.co
      - text: "RSS"
        href: /index.xml

format:
  html:
    include-in-header:
      - text: |
          <link rel="preload" href="/fonts/ibm-plex-sans-latin.woff2" as="font" type="font/woff2" crossorigin>
          <script src="https://cdn.usefathom.com/script.js" data-site="ZJFQREIA" defer></script>
    page-layout: "article"
    theme:
      - darkly
      - custom.scss
    grid:
      sidebar-width: 0px
      body-width: 700px
      margin-width: 276px
      gutter-width: 24px
    code-line-numbers: true
    mermaid:
      theme: dark

execute:
  freeze: auto
