---
aliases:
  - /posts/
listing:
  - id: posts
    contents: posts
    sort: "date desc"
    type: table
    fields: [date, title, reading-time]
    max-description-length: 100
    categories: true
    sort-ui: false
    filter-ui: false
    page-size: 10
    feed: true
  - id: today-i-learned
    contents: til
    type: table
    fields: [date, title, reading-time]
    categories: true
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    page-size: 10
    feed: true
page-layout: full
title-block-banner: true
---

Hi there 👋, I'm Dylan, an independent [AI consultant](https://iwanalabs.com).

I've been working in the AI & ML space for the [past 8 years](https://linkedin.com/in/dylanjcastillo) and have delivered projects for startups, large corporations, and government agencies. I also like working on [open-source projects](https://github.com/dylanjcastillo).

Here, you'll find a collection of my articles. I usually write about technical topics, but every once in a while I publish posts about financial independence or my end-of-year reviews.

If you'd like me to send you an email when I write new posts, you can [subscribe to my newsletter](https://subscribe.dylancastillo.co).

## Posts

These are longer posts covering mostly technical topics and a few personal posts such as yearly reviews.

:::{#posts}
:::

## Today I Learned (TIL)

I'm a big fan of [Simon Willison's "TIL" posts](https://til.simonwillison.net/), so I copied his idea.

They're a great way to force yourself to write more often by lowering the bar for what it's worth sharing.

These are short, less polished posts about things I've learned that I think others might find useful.

:::{#today-i-learned}
:::
