[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["Dylan Castillo <dylanjcastillo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
notebook = "^7.2.0"
openai = "^1.30.5"
google-generativeai = "^0.7.2"
numpy = "^2.1.0"
pandas = "^2.2.2"
python-dotenv = "^1.0.1"
scikit-learn = "^1.5.1"
pillow = "^10.4.0"
pydantic = "^2.9.2"
openpyxl = "^3.1.5"
langsmith = "^0.1.142"
scipy = "^1.14.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.7.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
