---
title: "$100M Leads"
subtitle: "Alex Hormozi"
date: 2024-05-28
highlights: 49
description-meta: "Kindle highlights from $100M Leads by Alex Hormozi."
book-cover: "https://m.media-amazon.com/images/I/71p5RV3janL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B0CFDR3TYV"
---

## Highlights

49 highlights.

> Advertising your core offer might be all you need to get leads to engage. Try this way first.
>
> [Page 50, location 730]{.highlight-ref}

> A lead magnet is a complete solution to a narrow problem. It’s typically a lower-cost or free offer to see who is interested in your stuff. And, once solved, it reveals another problem solved by your core offer.
>
> [Page 50, location 735]{.highlight-ref}

> A person who pays with their time now is more likely to pay with their money later.
>
> [Page 51, location 749]{.highlight-ref}

> if your audience has a problem they don’t know about, your lead magnet would make them aware of it.
>
> [Page 55, location 805]{.highlight-ref}

> The marketplace judges everything you have to offer - free or not. And you can never provide too much value. But, you can provide too little. So you want your lead magnet to provide so much value people feel obligated to pay you. The goal is to provide more value than the cost of your core offer before they’ve bought it.
>
> [Page 70, location 991]{.highlight-ref}

> If you give people a reason to take action, more people will do it. But a couple things to keep in mind: first, good reasons work better than bad reasons. And second, any reason (even bad ones) tends to work better than no reason at all.
>
> [Page 71, location 1025]{.highlight-ref}

> 1-to-1 to a Warm Audience = Warm Outreach
>
> 1-to-many to a Warm Audience = Posting Content
>
> 1-to-1 to a Cold Audience = Cold Outreach
>
> 1-to-many to a Cold Audience = Paid Ads
>
> These
>
> [Page 82, location 1178]{.highlight-ref}

> But, that last part - a way to communicate with people - is the most important part.
>
> [Page 88, location 1253]{.highlight-ref}

> If you struggle to give your stuff away for free, it means either people don’t want it (dream outcome), they don’t believe you (perceived likelihood of achievement) or the hidden costs (time, effort and sacrifice) are too high.
>
> [Page 106, location 1494]{.highlight-ref}

> Yeses give me opportunity. Nos give me feedback. Either way, I win.
>
> [Page 106, location 1507]{.highlight-ref}

> This means we have to: a)  Hook attention: get them to notice your content.
>
> b) Retain attention: get them to consume it.
>
> c)  Reward attention: satisfy the reason they consumed it to begin with.
>
> [Page 126, location 1747]{.highlight-ref}

> The smallest amount of material it takes to hook, retain and reward attention is a content unit.
>
> [Page 126, location 1755]{.highlight-ref}

> So there is no such thing as too long, only too boring.
>
> [Page 139, location 1956]{.highlight-ref}

> Clearly satisfy the hook you used to get their attention. In other words, completely answer the unresolved questions you embedded in their minds.
>
> [Page 141, location 1980]{.highlight-ref}

> So what do growing platforms do? They display lots of content without many advertisements at all. In short, they give give give…give give give…give give give…give give give…maybe ask. They dramatically over give and under ask.
>
> [Page 146, location 2029]{.highlight-ref}

> People are always waiting for you to ask for money. And when you don’t, they trust you more. They share your stuff more.
>
> [Page 146, location 2037]{.highlight-ref}

> 3) Puddles, Ponds, Lakes, Oceans. Narrow the focus of your content. If you have a small local business, you probably shouldn’t make general business content. Not at first, at least. Why? The audience will listen to people with better track records than you.
>
> [Page 159, location 2209]{.highlight-ref}

> Posting free content is less predictable than, but complementary to, warm reach outs.
>
> [Page 166, location 2303]{.highlight-ref}

> personalization and big fast value. This is important because they don't know us and they don’t trust us. We’ve gotta overcome both issues in a matter of seconds.
>
> [Page 187, location 2589]{.highlight-ref}

> I specifically call out ‘big fast value’ rather than “your lead magnet” as a reminder that it needs to be BIG FAST VALUE. If it’s not, or it’s mediocre, you’ll blend in with the ocean of people trying to get their attention. And they’ll treat you the same–they’ll ignore you.
>
> [Page 190, location 2634]{.highlight-ref}

> If your offer/lead magnet isn’t working for you, up the ante. Keep offering more until you make it so good they feel stupid saying no.
>
> [Page 190, location 2642]{.highlight-ref}

> You trade money for reach. A considerable advantage when you know what you’re doing. Ads are riskier. But, when done right, they can get you more leads than any other method.
>
> [Page 212, location 2917]{.highlight-ref}

> I've used it and gotten value from it as a consumer. So I have some idea how it works.
>
> I can target people on the platform interested in my stuff.
>
> I know how to format ads specific to the platform (which I’ll dive into in step three).
>
> I have the minimum amount of money to spend to place an ad.
>
> [Page 215, location 2962]{.highlight-ref}

> want to see how businesses do three things. 1) How they call out their ideal customers. 2) How they present the value elements. 3) How they give their audience a call to action.
>
> [Page 220, location 3019]{.highlight-ref}

> First, you reach out to people who know you. Then, you start making free content. Then you start reaching out to people who don’t know you. Then you start running paid ads. This is how you do the core four to get engaged leads.
>
> [Page 263, location 3661]{.highlight-ref}

> I like to ask myself: “Why are my customers too embarrassed to tell everyone they know about my product?” It may be okay, but it’s unremarkable, as in - not worthy of remark.
>
> [Page 299, location 4145]{.highlight-ref}

> There are two ways to build goodwill with your customers. You can lower your price or you can give more value.
>
> [Page 300, location 4161]{.highlight-ref}

> Rory Sutherland says, “Any fool can sell something for less.”
>
> [Page 301, location 4163]{.highlight-ref}

> Slowly lower the promises you make when making offers. Keep lowering them until your close rates lower. At that point, stop.
>
> [Page 305, location 4222]{.highlight-ref}

> The customer can get one win at the end of that week or win every day with daily progress updates. Same amount of progress, seven times the wins.
>
> [Page 308, location 4264]{.highlight-ref}

> Updates are wins. If it’s a bigger project, I share progress updates as frequently as possible.
>
> [Page 308, location 4271]{.highlight-ref}

> Customers form their lasting impression of a business within the first forty-eight hours after they buy.
>
> [Page 308, location 4273]{.highlight-ref}

> I got a slick saying from a public CEO friend of mine - BAMFAM: Book-A-Meeting-From-A-Meeting. Again, never leave a customer in no man’s land. They should always know what happens…next.
>
> [Page 308, location 4276]{.highlight-ref}

> Break down outcomes into the smallest possible increment. Communicate as often as reasonable (even if there is no progress, update them). Set timelines with breathing room. Deliver early.
>
> [Page 309, location 4283]{.highlight-ref}

> So test until you find something that works. Take massive action. Stay focused. Double down on it until it breaks. Then test until you find the next thing that works, and double down on that.
>
> [Page 406, location 5712]{.highlight-ref}

> You either win or you learn.
>
> [Page 406, location 5717]{.highlight-ref}

> Your speed to making big money depends on how fast you learn the skills to making big money.
>
> [Page 406, location 5721]{.highlight-ref}

> “Success comes down to doing the obvious thing for an uncommonly long period of time without convincing yourself you’re smarter than you are.”
>
> [Page 411, location 5797]{.highlight-ref}

> Most people, myself included, stop too soon. We don’t do enough.
>
> [Page 411, location 5799]{.highlight-ref}

> Reading doesn’t get people interested in the stuff you sell… advertising does. If you’re not telling anyone about the stuff you sell, then you aren’t getting anyone interested in the stuff you sell.
>
> [Page 417, location 5876]{.highlight-ref}

> You can fill out your one page advertising checklist in about five minutes. And once the naked truth stares back at you, all you have left is to do it.
>
> [Page 418, location 5889]{.highlight-ref}

> Level 1: Your friends know about the stuff you sell. To start getting engaged leads, you make one offer, to one avatar, on one platform. The moment you get engaged leads, is the moment you can start making money. For me, this started with reaching out to everyone I knew.
>
> [Page 421, location 5907]{.highlight-ref}

> Primary Action: Warm outreach.
>
> [Page 421, location 5912]{.highlight-ref}

> Level 2: You consistently let everyone you know about the stuff you sell. You know the exact inputs to get an engaged lead with your chosen advertising method. And, by scaling those inputs, you get consistent customers with it. But the consistent customers come from maximizing your personal work capacity. For me, on top of warm reach outs, I maximized my personal work capacity with paid aids, using a case study as my lead magnet. But looking back, I wish I would have started with posting free content. So I suggest that.
>
> [Page 421, location 5913]{.highlight-ref}

> Primary Actions: Do as much warm outreach and post as much content as you can consistently.
>
> [Page 421, location 5921]{.highlight-ref}

> Primary Action: You hire people to advertise profitably on your behalf.
>
> [Page 421, location 5928]{.highlight-ref}

> earning your
>
> [Location: 489]{.highlight-ref}

> 1-to-1 to a Warm Audience = Warm Outreach 1-to-many to a Warm Audience = Posting Content 1-to-1 to a Cold Audience = Cold Outreach 1-to-many to a Cold Audience = Paid Ads
>
> [Location: 1,178]{.highlight-ref}

> Steps are actions that must be done in a specific order to get a result. So steps are less flexible but have a more explicit reward. Lists can have just about anything on them in any order you want. So lists are more flexible but have a less explicit reward.
>
> [Location: 1,925]{.highlight-ref}
