---
title: "80/20 Running: Run Stronger and Race Faster by Training Slower"
subtitle: "Matt Fitzgerald and Robert Johnson"
date: 2022-04-05
highlights: 7
description-meta: "Kindle highlights from 80/20 Running: Run Stronger and Race Faster by Training Slower by Matt Fitzgerald and Robert Johnson."
book-cover: "https://m.media-amazon.com/images/I/91m-gHr2XBL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B00IIVFAEY"
---

## Highlights

7 highlights.

> Hard running isn’t repeatable, either physically or psychologically. If you do too much of it, your body will burn out if your mind doesn’t first.
>
> [Location: 82]{.highlight-ref}

> the typical elite runner does eight miles of easy running for every two miles of faster running.
>
> [Location: 88]{.highlight-ref}

> Do 80 percent of your running at low intensity and the other 20 percent at moderate to high intensity.
>
> [Location: 97]{.highlight-ref}

> Simply put: Running too hard too often is the single most common and detrimental mistake in the sport.
>
> [Location: 111]{.highlight-ref}

> Heart rate monitoring in particular is an effective tool for getting runners to slow down, while pace targets are better for getting runners to push themselves in the 20 percent of their workouts when they’re supposed to.
>
> [Location: 301]{.highlight-ref}

> The lactate threshold heart rate is associated with the fastest running pace at which a runner is able to talk comfortably. While wearing a heart rate monitor, start jogging at a slow, steady pace. After one minute, recite the Pledge of Allegiance (see Figure 6.3) and note your heart rate. Alternatively, count upward from 120 to 125. Now increase your speed slightly, wait a minute, recite the Pledge (or count) again, and again note your heart rate.
>
> [Location: 1,514]{.highlight-ref}

> Continue in this fashion until talking is slightly uncomfortable. Note your pace at the previous speed when speaking was comfortable or sort of comfortable. Your heart rate at that pace is your current lactate threshold heart rate. Comfortable in this context does not mean that you are able to talk without feeling any sense of dyspnea, or oxygen deficit, but the feeling should be quite mild.
>
> [Location: 1,517]{.highlight-ref}
