---
title: "Anything You Want"
subtitle: "Derek Sivers"
date: 2025-10-13
highlights: 5
description-meta: "Kindle highlights from Anything You Want by Derek Sivers."
---

## Notes

Fun to read and very applicable.

## Highlights

5 highlights added in October 2025.

> Give refunds. Give them attention. Take a little loss. You can afford it.
>
> [Page 47, location 315]{.highlight-ref}

> When someone’s doing something for love, being generous instead of stingy, trusting instead of fearful, it triggers this law: We want to give to those who give.
>
> [Page 50, location 332]{.highlight-ref}

> If you catch yourself about to say or write something that’s even the slightest bit aggressive, stop and replace it with something humble and generous.
>
> [Page 54, location 358]{.highlight-ref}

> CD Baby had some huge evangelists: people who loudly and constantly told everyone to use our company. When I looked back through their contact history, I saw that the first time they contacted us, they were loudly upset. Loud people are loud people, whether complaining or praising. So when you get some loud complaint, use that opportunity to make them so happy that they become a loud evangelist.
>
> [Page 54, location 363]{.highlight-ref}

> if there’s more than “two cents” worth of stuff that needs to change, then this rule does not apply. But if your contribution is small and just an opinion, let it go. Let the other person feel full ownership of the idea, instead.
>
> [Page 75, location 524]{.highlight-ref}
