---
title: "Breath: Improve your health and wellbeing by discovering the lost art of breathing"
subtitle: "James Nestor"
date: 2023-07-31
highlights: 4
description-meta: "Kindle highlights from Breath: Improve your health and wellbeing by discovering the lost art of breathing by James Nestor."
book-cover: "https://m.media-amazon.com/images/I/81YBM9VkrJL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B07Z49Z32V"
---

## Highlights

4 highlights.

> Mouthbreathing, it turns out, changes the physical body and transforms airways, all for the worse.15 Inhaling air through the mouth decreases pressure, which causes the soft tissues in the back of the mouth to become loose and flex inward, creating less space and making breathing more difficult. Mouthbreathing begets more mouthbreathing.
>
> [Location: 780]{.highlight-ref}

> Ninety percent of children have acquired some degree of deformity in their mouths and noses. Forty-five percent of adults snore occasionally, and a quarter of the population snores constantly.29 Twenty-five percent of American adults over 30 choke on themselves because of sleep apnea; and an estimated 80 percent of moderate or severe cases are undiagnosed.30, 31 Meanwhile, the majority of the population suffers from some form of breathing difficulty or resistance.
>
> [Location: 854]{.highlight-ref}

> “Carbon dioxide is, in fact, a more fundamental component of living matter than is oxygen.”
>
> [Location: 1,516]{.highlight-ref}

> When Buddhist monks chant their most popular mantra, Om Mani Padme Hum, each spoken phrase lasts six seconds, with six seconds to inhale before the chant starts again. The traditional chant of Om, the “sacred sound of the universe” used in Jainism and other traditions, takes six seconds to sing, with a pause of about six seconds to inhale. The sa ta na ma chant, one of the best-known techniques in Kundalini yoga, also takes six seconds to vocalize, followed by six seconds to inhale. Then there were the ancient Hindu hand and tongue poses called mudras. A technique called khechari, intended to help boost physical and spiritual health and overcome disease, involves placing the tongue above the soft palate so that it’s pointed toward the nasal cavity. The deep, slow breaths taken during this khechari each take six seconds. Japanese, African, Hawaiian, Native American, Buddhist, Taoist, Christian—these cultures and religions all had somehow developed the same prayer techniques, requiring the same breathing patterns.18 And they all likely benefited from the same calming effect.
>
> [Location: 1,567]{.highlight-ref}
