---
title: "Building a Second Brain: A Proven Method to Organize Your Digital Life and Unlock Your Creative Potential"
subtitle: "Tiago Forte"
date: 2022-06-25
highlights: 27
description-meta: "Kindle highlights from Building a Second Brain: A Proven Method to Organize Your Digital Life and Unlock Your Creative Potential by Tiago Forte."
book-cover: "https://m.media-amazon.com/images/I/71+IDmZU88L._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B09LVVN9L3"
---

## Highlights

27 highlights.

> What Is a Second Brain?
>
> [Location: 202]{.highlight-ref}

> The Legacy of Commonplace Books
>
> [Location: 230]{.highlight-ref}

> For centuries, artists and intellectuals from Leonardo da Vinci to Virginia Woolf, from John Locke to Octavia Butler, have recorded the ideas they found most interesting in a book they carried around with them, known as a “commonplace book.”
>
> [Location: 232]{.highlight-ref}

> The Digital Commonplace Book
>
> [Location: 254]{.highlight-ref}

> This digital commonplace book is what I call a Second Brain. Think of it as the combination of a study notebook, a personal journal, and a sketchbook for new ideas.
>
> [Location: 260]{.highlight-ref}

> Rethinking Notetaking: Notes as Knowledge Building Blocks
>
> [Location: 273]{.highlight-ref}

> Leveraging Technology as Thinking Tools
>
> [Location: 374]{.highlight-ref}

> The Superpowers of a Second Brain
>
> [Location: 422]{.highlight-ref}

> Second Brain Superpower \#1: Make Our Ideas Concrete
>
> [Location: 427]{.highlight-ref}

> Second Brain Superpower \#2: Reveal New Associations Between Ideas
>
> [Location: 444]{.highlight-ref}

> Second Brain Superpower \#3: Incubate Our Ideas Over Time
>
> [Location: 456]{.highlight-ref}

> Second Brain Superpower \#4: Sharpen Our Unique Perspectives
>
> [Location: 467]{.highlight-ref}

> American journalist, author, and filmmaker Sebastian Junger once wrote on the subject of “writer’s block”: “It’s not that I’m blocked. It’s that I don’t have enough research to write with power and knowledge about that topic. It always means, not that I can’t find the right words, \[but rather\] that I don’t have the ammunition.”7
>
> [Location: 478]{.highlight-ref}

> Remembering, Connecting, Creating: The Three Stages of Personal Knowledge Management
>
> [Location: 515]{.highlight-ref}

> Introducing The CODE Method: The Four Steps to Remembering What Matters
>
> [Location: 542]{.highlight-ref}

> Capture; Organize; Distill; Express.
>
> [Location: 544]{.highlight-ref}

> Capture: Keep What Resonates
>
> [Location: 556]{.highlight-ref}

> By training ourselves to notice when something resonates with us, we can improve not only our ability to take better notes, but also our understanding of ourselves and what makes us tick.
>
> [Location: 571]{.highlight-ref}

> Instead of jumping at every new headline and notification, we can choose to consume information that adds value to our lives and consciously let go of the rest.
>
> [Location: 574]{.highlight-ref}

> Organize: Save for Actionability
>
> [Location: 575]{.highlight-ref}

> The best way to organize your notes is to organize for action, according to the active projects you are working on right now. Consider new information in terms of its utility, asking, “How is this going to help me move forward one of my current projects?”
>
> [Location: 583]{.highlight-ref}

> Distill: Find the Essence
>
> [Location: 589]{.highlight-ref}

> Every time you take a note, ask yourself, “How can I make this as useful as possible for my future self?” That question will lead you to annotate the words and phrases that explain why you saved a note, what you were thinking, and what exactly caught your attention.
>
> [Location: 604]{.highlight-ref}

> Express: Show Your Work
>
> [Location: 608]{.highlight-ref}

> All the previous steps—capturing, organizing, and distilling—are geared toward one ultimate purpose: sharing your own ideas, your own story, and your own knowledge with others. What is the point of knowledge if it doesn’t help anyone or produce anything?
>
> [Location: 608]{.highlight-ref}

> Building a Private Collection of Knowledge
>
> [Location: 680]{.highlight-ref}

> Creating a Knowledge Bank: How to Generate Compounding Interest from Your Thoughts
>
> [Location: 715]{.highlight-ref}
