---
title: "Cómo fracasar en casi todo y aun así triunfar: Algo así como la historia de mi vida (Gestion Del Conocimiento) (Spanish Edition)"
subtitle: "Scott Adams and Daniel Menezo García"
date: 2021-05-28
highlights: 18
description-meta: "Kindle highlights from Cómo fracasar en casi todo y aun así triunfar: Algo así como la historia de mi vida (Gestion Del Conocimiento) (Spanish Edition) by Scott Adams and Daniel Menezo García."
book-cover: "https://m.media-amazon.com/images/I/711-RfgM6ML._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B01B616SQG"
---

## Highlights

18 highlights.

> En los años posteriores, a medida que el negocio caía en picado, mi pasión se convirtió en frustración y en contrariedad. La pasión se esfumó.
>
> [Location: 360]{.highlight-ref}

> El éxito fue la causa de la pasión más a menudo que al revés.
>
> [Location: 365]{.highlight-ref}

> la pasión puede ser un indicador sencillo del talento. Los humanos tendemos a disfrutar haciendo lo que se nos da bien, y a no disfrutar haciendo lo que se nos da de pena.
>
> [Location: 366]{.highlight-ref}

> La energía es buena. La pasión es una chorrada.
>
> [Location: 379]{.highlight-ref}

> Yo soy optimista por naturaleza, o quizá por la educación que recibí (cuesta saber dónde acaba la una y empieza la otra), pero sea cual sea la causa, hace mucho tiempo que considero que el fracaso es un instrumento, no un resultado.
>
> [Location: 391]{.highlight-ref}

> Ésta fue la primera vez que entré en contacto con la idea de que uno debe tener un sistema en vez de una meta. El sistema consistía en no dejar nunca de buscar mejores opciones.
>
> [Location: 696]{.highlight-ref}

> Si usted alcanza su meta, lo celebra y se siente genial, pero sólo hasta que se da cuenta de que ha perdido aquello que le daba propósito y dirección.
>
> [Location: 716]{.highlight-ref}

> Para nuestro propósito diremos que una meta es un objetivo específico que usted alcanzará o no en el futuro. Un sistema es algo que hace regularmente y que aumenta sus probabilidades de ser feliz a largo plazo. Si usted hace algo todos los días, es un sistema. Si espera conseguir algo en un momento futuro, es una meta.
>
> [Location: 730]{.highlight-ref}

> Cuando los que persiguen metas triunfan a lo grande, esto es noticia y constituye una historia interesante. Eso le ofrece una visión distorsionada del éxito que obtienen las personas que se fijan metas.
>
> [Location: 739]{.highlight-ref}

> Siempre se preguntará si está siendo demasiado egocéntrico o lo es demasiado poco.
>
> [Location: 1,001]{.highlight-ref}

> El tipo más importante de egoísmo conlleva dedicar tiempo a su estado físico, su dieta, el desarrollo de su carrera profesional y el tiempo de calidad dedicado a su familia y a sus amigos.
>
> [Location: 1,020]{.highlight-ref}

> La manera en la que abordo el problema de las prioridades múltiples es centrándome en un solo baremo principal: mi energía. Elijo cosas que maximizan mi energía personal porque eso me facilita gestionar todas las demás prioridades.
>
> [Location: 1,071]{.highlight-ref}

> al convertirse en una persona con una gran energía, usted anima a las personas que le rodean. Este cambio positivo mejorará su vida social, amorosa, familiar y laboral.
>
> [Location: 1,082]{.highlight-ref}

> Generalmente, la simplificación es la estrategia de las personas que ven el mundo como un conjunto de sistemas.
>
> [Location: 1,233]{.highlight-ref}

> Los sistemas complejos tienen más probabilidades de fracasar.
>
> [Location: 1,234]{.highlight-ref}

> Probablemente los sistemas simples son la mejor manera de alcanzar el éxito. Una vez tiene usted éxito, la optimización empieza a tener más valor. Las personas y las empresas de éxito tienen el lujo de poder optimizar su actividad con el paso del tiempo para que sea cada vez más perfecta.
>
> [Location: 1,235]{.highlight-ref}

> Me explicó que, en el caso de los programas para televisión, el mejor indicador no es la respuesta media. La media no significa mucho para los productos de ocio. Lo que buscan los responsables es una reacción inusualmente fuerte por parte de un subsector del público, aunque la mayoría aborrezca el programa.
>
> [Location: 1,845]{.highlight-ref}

> Por lo tanto, la primera parte de mi sistema supone gestionar mis estados mental y físico, de modo que pueda hacer más cosas con el tipo correcto de energía.
>
> [Location: 4,674]{.highlight-ref}
