---
title: "Confesiones de un joven novelista (Spanish Edition)"
subtitle: "Umberto Eco and Guillermo Sans Mora"
date: 2021-11-10
highlights: 7
description-meta: "Kindle highlights from Confesiones de un joven novelista (Spanish Edition) by Umberto Eco and Guillermo Sans Mora."
book-cover: "https://m.media-amazon.com/images/I/81x+tZTpN6L._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B006543JAS"
---

## Highlights

7 highlights.

> un Tolstói traducido es más fiel al original que cualquier traducción inglesa de
>
> [Location: 39]{.highlight-ref}

> Heidegger o Lacan. ¿Es Lacan más «creativo» que Cervantes?
>
> [Location: 40]{.highlight-ref}

> Todo libro científico debe ser una especie de historia policíaca, el relato de la búsqueda de algún Santo Grial. Y creo que eso es lo que he hecho desde entonces en todas mis obras académicas.
>
> [Location: 80]{.highlight-ref}

> Hasta ahora, he dicho que 1) mi punto de partida es una idea fecunda o una imagen, y 2) que la construcción del mundo narrativo marca el estilo de la novela.
>
> [Location: 236]{.highlight-ref}

> Un buen diccionario debe ser circular, debe decir qué significa la palabra «gato» usando otras palabras; de otro modo, bastaría con cerrar el diccionario, señalar a un gato y decir: «Esto es un gato».
>
> [Location: 378]{.highlight-ref}

> si bien puede resultar difícil decidir si una interpretación determinada es buena, o decidir cuál de las dos interpretaciones de un mismo texto es mejor, siempre es posible ver que una interpretación determinada es descaradamente falsa, alocada o descabellada.
>
> [Location: 393]{.highlight-ref}

> El Papa y el Dalai Lama pueden pasarse años discutiendo si es cierto que Jesucristo es el hijo de Dios, pero (si están bien informados sobre literatura y cómics) ambos tienen que admitir que Clark Kent es Supermán, y viceversa.
>
> [Location: 981]{.highlight-ref}
