---
title: "Dominion: The Making of the Western Mind"
subtitle: "Tom Holland"
date: 2026-09-03
highlights: 7
description-meta: "Kindle highlights from Dominion: The Making of the Western Mind by Tom Holland."
book-cover: "https://m.media-amazon.com/images/I/81YZx0MZWjL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B010RGSEC2"
---

## Highlights

7 highlights.

> ‘Patience in tribulation, offering the other cheek, praying for one’s enemies, loving those who hate us’:19
>
> [Page 17, location 235]{.highlight-ref}

> That Christians had been willing to die as witnesses for their beliefs, as martyrs, was precisely what had marked them out to the Roman authorities as sinister and aberrant.
>
> [Page 19, location 270]{.highlight-ref}

> My ambition is hubristic enough as it is: to explore how we in the West came to be what we are, and to think the way that we do.
>
> [Page 21, location 292]{.highlight-ref}

> To live in a Western country is to live in a society still utterly saturated by Christian concepts and assumptions.
>
> [Page 21, location 299]{.highlight-ref}

> To argue that, in the West, the ‘pretty widespread consensus of what’s right and what’s wrong’ derives principally from Christian teachings and presumptions can risk seeming, in societies of many faiths and none, almost offensive
>
> [Page 23, location 325]{.highlight-ref}

> So profound has been the impact of Christianity on the development of Western civilisation that it has come to be hidden from view. It is the incomplete revolutions which are remembered; the fate of those which triumph is to be taken for granted.
>
> [Page 26, location 363]{.highlight-ref}

> Just as the Bishop of Oxford refused to consider that he might be descended from an ape, so now are many in the West reluctant to contemplate that their values, and even their very lack of belief, might be traceable back to Christian origins.
>
> [Location: 324]{.highlight-ref}
