---
title: "Get Strong: The Ultimate 16-Week Transformation Program For Gaining Muscle and Strength--Using The Power Of Progressive Calisthenics"
subtitle: "Al Kavadlo, Danny Kavadlo, and Mark Sisson"
date: 2022-04-11
highlights: 6
description-meta: "Kindle highlights from Get Strong: The Ultimate 16-Week Transformation Program For Gaining Muscle and Strength--Using The Power Of Progressive Calisthenics by Al Kavadlo, Danny Kavadlo, and Mark Sisson."
book-cover: "https://m.media-amazon.com/images/I/915FqpQcMFL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B071VM4FZD"
---

## Highlights

6 highlights.

> The only way to get stronger is to learn a movement pattern under a relatively low amount of resistance, then gradually increase the load and/or quantity of repetitions as the body adapts.
>
> [Location: 185]{.highlight-ref}

> One way is to change the weight-to-limb ratio, which can be achieved by placing more (or less) of our weight in our hands or feet. To illustrate this, compare a push-up with your feet on an elevated surface to a push-up with all your limbs on the ground.
>
> [Location: 191]{.highlight-ref}

> Another way to progress your training is to remove contact points entirely. A one-legged squat will always require more strength than a standard two-legged squat.
>
> [Location: 195]{.highlight-ref}

> Our five warm-up exercises are: Wrist Roll, Reach and Touch, Downdog/Updog Switch, Hollow Body and Plank.
>
> [Location: 239]{.highlight-ref}

> Every book on goal setting tells you to tell your friends about your goals. Telling people gives you accountability, they say. Blah, blah, blah. I already know from over a decade in the personal training industry that that plan doesn’t tend to work. Many people talk a good game, but never put their words into action. Talking is talking. Doing is doing. They aren’t the same thing.
>
> [Location: 1,518]{.highlight-ref}

> When we forget the goal, we have no choice but to focus on the process itself. If you are always focused on goals, you will miss the entire journey. Instead, focus on doing each little task along the way with care and attention. Get lost in the moment; it is the only path to true joy.
>
> [Location: 1,543]{.highlight-ref}
