---
title: "Imperium"
subtitle: "Robert Harris"
date: 2026-09-03
highlights: 1
description-meta: "Kindle highlights from Imperium by Robert Harris."
book-cover: "https://m.media-amazon.com/images/I/81QaknIlZxL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B0041RRH7W"
---

## Notes

I liked following Cicero’s rise as an outsider through the ranks to the consulship. I also found the antagonism between patricians and populists interesting, and how having money didn’t necessarily mean you’d be accepted by the elite.

He knew how to play politics, getting his enemies to fight among themselves and often persuading them to see him as an ally. That helped him rise. I also found it interesting that he was willing to challenge Crassus, potentially the richest and one of the most powerful men in Rome.

I’d start with *Imperium* and then read *Rubicon*. It makes *Rubicon* much more interesting.

## Highlights

1 highlight added in August 2026.

> if you must do something unpopular, you might as well do it wholeheartedly, for in politics there is no credit to be won by timidity.
>
> [Page 74, location 883]{.highlight-ref}
