---
title: "Made to Stick: Why some ideas take hold and others come unstuck"
subtitle: "Chip Heath and Dan Heath"
date: 2024-11-03
highlights: 6
description-meta: "Kindle highlights from Made to Stick: Why some ideas take hold and others come unstuck by Chip Heath and Dan Heath."
book-cover: "https://m.media-amazon.com/images/I/71dief0Ab1L._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B0031RS2XG"
---

## Highlights

6 highlights.

> THOSE ARE THE six principles of successful ideas. To summarize, here’s our checklist for creating a successful idea: a Simple Unexpected Concrete Credentialed Emotional Story.
>
> [Page: 18]{.highlight-ref}

> Fortunately, JFK was more intuitive than a modern-day CEO; he knew that opaque, abstract missions don’t captivate and inspire people.
>
> [Page: 21]{.highlight-ref}

> All creative ads resemble one another, but each loser is uncreative in its own way.
>
> [Page: 23]{.highlight-ref}

> If you want to spread your ideas to other people, you should work within the confines of the rules that have allowed other ideas to succeed over time. You want to invent new ideas, not new rules.
>
> [Page: 24]{.highlight-ref}

> For an idea to stick, for it to be useful and lasting, it’s got to make the audience: Pay attention Understand and remember it Agree/Believe Care Be able to act on it
>
> [Page: 246]{.highlight-ref}

> Pay attention: UNEXPECTED 2. Understand and remember it: CONCRETE 3. Agree/Believe: CREDIBLE 4. Care: EMOTIONAL 5. Be able to act on it: STORY
>
> [Page: 246]{.highlight-ref}
