---
title: "More Than Happiness: Buddhist and Stoic Wisdom for a Sceptical Age"
subtitle: "Antonia Macaro"
date: 2021-12-30
highlights: 4
description-meta: "Kindle highlights from More Than Happiness: Buddhist and Stoic Wisdom for a Sceptical Age by Antonia Macaro."
book-cover: "https://m.media-amazon.com/images/I/91r3giCTKPL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B076PMG5JB"
---

## Highlights

4 highlights.

> Their way of dealing with suffering rests not on the promise of a blissful afterlife but on a deep suspicion of the urge to find fulfilment in worldly goods and activities. It’s not by pursuing but by abandoning our desires that real satisfaction can be found.
>
> [Location: 337]{.highlight-ref}

> a universal feature of life: whether we are actively suffering or not, no worldly thing or pleasure can give us lasting satisfaction.
>
> [Location: 361]{.highlight-ref}

> At the end of the Buddha’s first discourse, one of the monks has an insight that is expressed succinctly as: ‘Whatever is subject to origination is all subject to cessation’,
>
> [Location: 377]{.highlight-ref}

> When walking along a street, remind yourself that there was a time when none of these buildings stood, and that none will last forever. When you admire a beautiful flower, remember that you are seeing only one moment in the life course of the plant. More awesome still is the experience of looking at a mountainous landscape, knowing that every contour was carved by millennia of ice, rain and wind.
>
> [Location: 380]{.highlight-ref}
