---
title: "Nietzsche: Philosopher, Psychologist, Antichrist (Princeton Classics)"
subtitle: "Walter A. Kaufmann and Alexander Nehamas"
date: 2025-06-19
highlights: 4
description-meta: "Kindle highlights from Nietzsche: Philosopher, Psychologist, Antichrist (Princeton Classics) by Walter A. Kaufmann and Alexander Nehamas."
book-cover: "https://m.media-amazon.com/images/I/71264kTc-TL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B00F8MIJXK"
---

## Highlights

4 highlights.

> the overman is able to face Nietzsche’s notorious thought of “the eternal recurrence,” which Kaufmann takes, controversially, to hold that the universe repeats itself in exactly the same way over and over without end, without purpose or resting point. Only the overman, according to this interpretation, can bear the thought that the world has no inherent purpose and life no intrinsic meaning, for the overman gives his life a meaning of its own.
>
> [Location: 83]{.highlight-ref}

> Here the ways of men part: if you wish to strive for peace of soul and pleasure, then believe; if you wish to be a devotee of truth, then inquire.—LETTER TO HIS SISTER, June 11, 1865.
>
> [Page: 21]{.highlight-ref}

> I am impassioned for independence; I sacrifice all for it … and am tortured more by all the smallest strings than others are by chains.—XXI, 88.
>
> [Page: 21]{.highlight-ref}

> Every true faith is infallible inasmuch as it accomplishes what the person who has the faith hopes to find in it; but faith does not offer the least support for a proof of objective truth.
>
> [Page: 23]{.highlight-ref}
