---
title: "Rubicon: The Triumph and Tragedy of the Roman Republic"
subtitle: "Tom Holland"
date: 2026-09-03
highlights: 9
description-meta: "Kindle highlights from Rubicon: The Triumph and Tragedy of the Roman Republic by Tom Holland."
book-cover: "https://m.media-amazon.com/images/I/810kJDG+26L._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B004YD1RYM"
---

## Notes

Fun and insightful, although it can get a bit dense if you’re not familiar enough with the period and the characters. It gives you a good sense of the years leading up to the fall of the Republic.

You might blame Caesar’s ambition for the fall, but Crassus and Pompey seemed to be pursuing similar goals. It left me feeling that the Republic’s fall was almost inevitable.

I also see parallels with the US today, with people in power continually pushing to shape conditions in their own favor. Trump seemingly pushing to remove reelection limits, centralize power, and make greater use of the military came to mind while reading.

## Highlights

9 highlights added between December 2025 and September 2026.

> The Romans, being a people as practical as they were devout, had no patience with fatalism. They were interested in knowing the future only because they believed that it could then better be kept at bay.
>
> [Page 3, location 373]{.highlight-ref}

> How typical of the Greeks to reduce the ideal of shared citizenship to sophistry! To a Roman, nothing was more sacred or cherished.
>
> [Page 4, location 391]{.highlight-ref}

> Praise was what every citizen most desired – just as public shame was his ultimate dread.
>
> [Page 5, location 398]{.highlight-ref}

> To place personal honour above the interests of the entire community was the behaviour of a barbarian – or worse yet, a king.
>
> [Page 5, location 401]{.highlight-ref}

> The ideal of an assembly rich in experience and wisdom, acting as a brake on such irresponsible elements as the young or indigent poor, was one dear to every conservative’s heart.
>
> [Page 104, location 1766]{.highlight-ref}

> nothing was more scandalous to the Romans than a reputation for enjoying haute cuisine. Celebrity chefs had long been regarded as a particularly pernicious symptom of decadence.
>
> [Page 186, location 2917]{.highlight-ref}

> For as long as there were restless tribes beyond the Roman frontier, ignorant of the conventions of civilised behaviour, the danger would persist.
>
> [Page 244, location 3735]{.highlight-ref}

> ‘It is disturbing’, Cicero reflected, ‘that it tends to be men of genius and brilliance who are consumed by the desire for endless magistracies and military commands, and by the lust for power and glory.’5
>
> [Page 264, location 4014]{.highlight-ref}

> What mattered was not the form but the reality of power. And Caesar, unlike Sulla, had no intention of relinquishing it.
>
> [Page 345, location 5180]{.highlight-ref}
