---
title: "The Carnivore Code: Unlocking the Secrets to Optimal Health by Returning to Our Ancestral Diet"
subtitle: "Paul Saladino MD"
date: 2021-12-08
highlights: 5
description-meta: "Kindle highlights from The Carnivore Code: Unlocking the Secrets to Optimal Health by Returning to Our Ancestral Diet by Paul Saladino MD."
book-cover: "https://m.media-amazon.com/images/I/A1HdkwYSp2L._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B089KB41VC"
---

## Highlights

5 highlights.

> Throughout my medical training and practice within mainstream allopathic medicine, I’ve come to one very disappointing conclusion: the system that I was trained in isn’t helping people lead better lives. Sure, it can correct acute problems like a ruptured appendix or a broken leg, but when it comes to chronic disease and correcting the root cause of illness, it’s failing miserably.
>
> [Location: 92]{.highlight-ref}

> We are the humans we are today because we began eating animals.
>
> [Page: 6]{.highlight-ref}

> Protein is best thought of as a building block, while fat and carbohydrates fuel the metabolic engine. Once we’ve obtained enough protein to grow and repair the structural components of our body, more of this macronutrient doesn’t seem to be helpful, and too much might tax our system in the excretion process of excess nitrogen groups from amino acids.89
>
> [Page: 237]{.highlight-ref}

> The equation for living a radical life is simple: eating animals nose-to-tail provides all of the nutrients we need to thrive with no associated toxins. We must also be outside in the sun—playing, hunting, and exploring—and sleeping in the dark at night, free from the incessant, low-level stress we all face in Western society. A bit of heat, cold, and some intense exercise are other important parts of this equation, as is spending time with family and community while giving and receiving love as we pursue something we are passionate about in our lives.
>
> [Page: 245]{.highlight-ref}

> When it comes to understanding which foods are damaging our guts and triggering our immune systems, elimination is an extremely powerful tool.
>
> [Page: 249]{.highlight-ref}
