---
title: "The Devils"
subtitle: "Joe Abercrombie"
date: 2026-08-15
highlights: 3
description-meta: "Kindle highlights from The Devils by Joe Abercrombie."
book-cover: "https://m.media-amazon.com/images/I/71S-aepopBL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B0D3CB76TV"
---

## Notes

This is my least favorite book by Joe Abercrombie. The characters were mostly predictable, and the conflict felt unoriginal. Duke Michael of Nicaea was about as clichéd an evil villain as you can get.

The story felt a bit like an ugly-duckling-to-swan arc, with constant romantic relationships among the main characters. There were seven of them, and six got paired up and mostly ended up fucking. At one point, they even fucked in the middle of a battle. It felt a bit forced.

## Highlights

3 highlights added between July and August 2026.

> alive under there, niggling and gnawing.
>
> [Page 124, location 2318]{.highlight-ref}

> “The Chapel of the Holy Expediency has its drawbacks,” said Sunny, “but I take pride in being part of an elite team. Including the man who can’t step off a boat and the woman who can’t unlock an open door.”
>
> [Page 165, location 3112]{.highlight-ref}

> What manner of person needs constantly to assert their own importance, after all? Only the truly unimportant.
>
> [Page 396, location 7463]{.highlight-ref}
