---
title: "The Heart Of Buddha's Teaching: Transforming Suffering into Peace, Joy and Liberation"
subtitle: "Thich Nhat Hanh"
date: 2019-01-19
highlights: 4
description-meta: "Kindle highlights from The Heart Of Buddha's Teaching: Transforming Suffering into Peace, Joy and Liberation by Thich Nhat Hanh."
book-cover: "https://m.media-amazon.com/images/I/91iXwzjS9dL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B0031RS9RK"
---

## Highlights

4 highlights.

> meditation community in southwestern France, where he teaches, writes, gardens and aids refugees worldwide. 'Thich Nhat Hanh writes with the voice of the Buddha.' Sogyal Rinpoche 'Thich Nhat Hanh is more my brother than many who are nearer to me in race and nationality, because he and I see things in exactly the same way.' Thomas Merton Other Books by Thich Nhat Hanh Be Still and Know Being Peace The Blooming of a Lotus Breathe! You Are Alive Call Me by My True Names Cultivating the Mind of Love The Diamond That Cuts through Illusion For a Future To Be Possible Fragrant Palm Leaves The Heart of Understanding Hermitage among the Clouds Interbeing Living Buddha, Living Christ The Long Road Turns to Joy Love in Action The Miracle of Mindfulness Old Path White Clouds
>
> [Location: 38]{.highlight-ref}

> southwestern France, where he teaches, writes, gardens and
>
> [Location: 38]{.highlight-ref}

> Peace Is Every Step
>
> [Location: 47]{.highlight-ref}

> If we hurt someone and regret it, that regret is wholesome. But if our regret leads to a guilt complex that colors whatever we do in the future, that regret can be called unwholesome.
>
> [Location: 1,077]{.highlight-ref}
