---
title: "The 4-Hour Work Week: Escape the 9-5, Live Anywhere and Join the New Rich"
subtitle: "Timothy Ferriss"
date: 2022-01-23
highlights: 17
description-meta: "Kindle highlights from The 4-Hour Work Week: Escape the 9-5, Live Anywhere and Join the New Rich by Timothy Ferriss."
book-cover: "https://m.media-amazon.com/images/I/71DPD5QEZCL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B006X0M2TS"
---

## Highlights

17 highlights.

> Uncertainty and the prospect of failure can be very scary noises in the shadows. Most people will choose unhappiness over uncertainty.
>
> [Location: 781]{.highlight-ref}

> The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man. —GEORGE BERNARD SHAW,
>
> [Location: 911]{.highlight-ref}

> The level of competition is thus fiercest for “realistic” goals, paradoxically making them the most time and energy-consuming. It is easier to raise \$1,000,000 than it is \$100,000. It is easier to pick up the one perfect 10 in the bar than the five 8s.
>
> [Location: 941]{.highlight-ref}

> If you are insecure, guess what? The rest of the world is, too. Do not overestimate the competition and underestimate yourself. You are better than you think.
>
> [Location: 943]{.highlight-ref}

> 1. Doing something unimportant well does not make it important. 2. Requiring a lot of time does not make a task important.
>
> [Location: 1,220]{.highlight-ref}

> What you do is infinitely more important than how you do it.
>
> [Location: 1,222]{.highlight-ref}

> Slow down and remember this: Most things make no difference. Being busy is a form of laziness—lazy thinking and indiscriminate action.
>
> [Location: 1,303]{.highlight-ref}

> Being selective—doing less—is the path of the productive. Focus on the important few and ignore the rest.
>
> [Location: 1,305]{.highlight-ref}

> Parkinson’s Law dictates that a task will swell in (perceived) importance and complexity in relation to the time allotted for its completion.
>
> [Location: 1,342]{.highlight-ref}

> Identify the few critical tasks that contribute most to income and schedule them with very short and clear deadlines.
>
> [Location: 1,351]{.highlight-ref}

> At least three times per day at scheduled times, he had to ask himself the following question: Am I being productive or just active?
>
> [Location: 1,385]{.highlight-ref}

> Stop asking for opinions and start proposing solutions.
>
> [Location: 1,482]{.highlight-ref}

> Any man who reads too much and uses his own brain too little falls into lazy habits of thinking.
>
> [Location: 1,511]{.highlight-ref}

> Most information is time-consuming, negative, irrelevant to your goals, and outside of your influence. I challenge you to look at whatever you read or watched today and tell me that it wasn’t at least two of the four.
>
> [Location: 1,531]{.highlight-ref}

> Think back to your days on the playground. There was always a big bully and countless victims, but there was also that one small kid who fought like hell, thrashing and swinging for the fences. He or she might not have won, but after one or two exhausting exchanges, the bully chose not to bother him or her. It was easier to find someone else. Be that kid.
>
> [Location: 1,669]{.highlight-ref}

> resolve to keep those around you focused and avoid all meetings, whether in person or remote, that do not have clear objectives. It is possible to do this tactfully, but expect that some time wasters will be offended the first few times their advances are rejected.
>
> [Location: 1,772]{.highlight-ref}

> If you are a micromanaging entrepreneur, realize that even if you can do something better than the rest of the world, it doesn’t mean that’s what you should be doing if it’s part of the minutiae. Empower others to act without interrupting you.
>
> [Location: 1,942]{.highlight-ref}
