---
title: "¿Tienes una startup?: Todas las claves para conseguir financiación (Gestión 2000) (Spanish Edition)"
subtitle: "Luis Martín Cabiedes"
date: 2022-03-20
highlights: 13
description-meta: "Kindle highlights from ¿Tienes una startup?: Todas las claves para conseguir financiación (Gestión 2000) (Spanish Edition) by Luis Martín Cabiedes."
book-cover: "https://m.media-amazon.com/images/I/81sTf22qqgL._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B00XM0NR64"
---

## Highlights

13 highlights.

> Una vez más se comprueba que cuando te crees único es que has leído poco.
>
> [Location: 151]{.highlight-ref}

> Muchos creen que tener libertad es no tener jefe, pero yo creo que también lo es no tener empleados.
>
> [Location: 164]{.highlight-ref}

> en el mar, cuando ves que se acerca una tormenta, los pesimistas creen que irá a peor; los optimistas, que mejorará por sí sola, pero los marineros sensatos preferimos ajustar las velas.
>
> [Location: 171]{.highlight-ref}

> «Cuando soplan vientos de cambio, unos buscan refugios y se ponen a salvo y otros construyen molinos y se hacen ricos.»
>
> [Location: 188]{.highlight-ref}

> prueba a fondo tu mercado y cuando tengas algo realmente bueno que exportar, sácalo al mundo sin complejos.
>
> [Location: 245]{.highlight-ref}

> Todos los buenos emprendedores son así, pero lo curioso es que todos los malos también.
>
> [Location: 563]{.highlight-ref}

> en internet no todo está inventado, pero sí está todo intentado.
>
> [Location: 832]{.highlight-ref}

> «Cuando el modelo de negocio sea repetible y escalable, entonces es cuando hay que recaudar dinero».
>
> [Location: 1,269]{.highlight-ref}

> Hoy ya no puede llegar un emprendedor ante un inversor sin haber hecho una prueba de algo, sin algo que vaya más allá de un análisis de mercado.
>
> [Location: 1,313]{.highlight-ref}

> En general, con los inversores se ha de hablar su idioma, no el propio.
>
> [Location: 1,374]{.highlight-ref}

> ¿Qué es lo que desea sacar en claro de una primera entrevista?
>
> [Location: 1,613]{.highlight-ref}

> cuál es la unidad básica de vuestro negocio, aquello que vamos a multiplicar para hacer rentables los resultados: vosotros compráis a tanto, vendéis a tanto, luego quedará un margen unitario de tanto. También, cuánto os cuesta cada nuevo usuario o cliente.
>
> [Location: 1,614]{.highlight-ref}

> las oportunidades que los inversores buscamos son aquellas que ve todo el mundo, pero en las que el proyecto que te presentan demuestra poseer una clara ventaja competitiva,
>
> [Location: 1,926]{.highlight-ref}
