---
title: "Who Gets What—and Why: The New Economics of Matchmaking and Market Design"
subtitle: "Alvin E. Roth"
date: 2016-08-29
highlights: 10
description-meta: "Kindle highlights from Who Gets What—and Why: The New Economics of Matchmaking and Market Design by Alvin E. Roth."
book-cover: "https://m.media-amazon.com/images/I/71Cz1F64n9L._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B00LZ7GQJQ"
---

## Highlights

10 highlights.

> Markets differ from central planning because no one but the participants themselves determines who gets what. And marketplaces differ from anything-goes laissez-faire because participants enter the marketplace knowing that it has rules.
>
> [Page: 7]{.highlight-ref}

> Repugnance shows with particular clarity what
>
> [Page: 12]{.highlight-ref}

> all markets reveal: people’s values, desires, and beliefs.
>
> [Page: 12]{.highlight-ref}

> “What do you know when you see a green plant in the desert?” he asked. I shook my head, and he exclaimed: “It’s poison! Otherwise something would have eaten it by now.”
>
> [Page: 13]{.highlight-ref}

> The key to such a clearinghouse is making it safe for people to state their preferences honestly.
>
> [Page: 112]{.highlight-ref}

> flawed markets can undermine not just communities but whole nations. The Berlin Wall was a monument to that fact.
>
> [Page: 168]{.highlight-ref}

> paradox of market design that as communication gets easier and cheaper, it sometimes also gets less informative.
>
> [Page: 169]{.highlight-ref}

> When talk is cheap, it doesn’t reliably signal anything.
>
> [Page: 176]{.highlight-ref}

> That’s why one of the ancient uses of auctions is called price discovery: letting the market tell you what price you can get for what you are selling, and to whom you should sell it to get that price.
>
> [Page: 185]{.highlight-ref}

> should never forget that markets are human artifacts.
>
> [Page: 212]{.highlight-ref}
