---
title: "Why We Get Fat: And What to Do About It"
subtitle: "Gary Taubes"
date: 2022-02-21
highlights: 61
description-meta: "Kindle highlights from Why We Get Fat: And What to Do About It by Gary Taubes."
book-cover: "https://m.media-amazon.com/images/I/81c+FytgM+L._SY160.jpg"
amazon-url: "https://www.amazon.com/dp/B003WUYOQ6"
---

## Highlights

61 highlights.

> If so many people are getting fat and diabetic in large part because we’ve been getting the wrong advice, we should not be dawdling about determining that with certainty.
>
> [Location: 91]{.highlight-ref}

> “the physician is called upon only to do a special trick, to make the patient do something—stop eating—after it has already been proved that he cannot do it.”
>
> [Page: 5]{.highlight-ref}

> “The fundamental cause of obesity and overweight,” as the World Health Organization says, “is an energy imbalance between calories consumed on one hand, and calories expended on the other hand.”\*
>
> [Page: 6]{.highlight-ref}

> This way of thinking about our weight is so compelling and so pervasive that it is virtually impossible nowadays not to believe it.
>
> [Page: 6]{.highlight-ref}

> I will argue in this book that the fault lies entirely with the medical orthodoxy—both the belief that excess fat is caused by consuming excess calories, and the advice that stems from it.
>
> [Page: 8]{.highlight-ref}

> two factors will essentially determine how much fat we accumulate, both having to do with the hormone insulin.
>
> [Page: 9]{.highlight-ref}

> First, when insulin levels are elevated, we accumulate fat in our fat tissue; when these levels fall, we liberate fat from the fat tissue and burn it for fuel.
>
> [Page: 10]{.highlight-ref}

> Second, our insulin levels are effectively determined by the carbohydrates we eat—not entirely, but for all intents and purposes.
>
> [Page: 10]{.highlight-ref}

> The more carbohydrates we eat, and the easier they are to digest and the sweeter they are, the more insulin we will ultimately secrete, meaning that the level of it in our bloodstream is greater and so is the fat we retain in our fat cells.
>
> [Page: 10]{.highlight-ref}

> The science tells us that obesity is ultimately the result of a hormonal imbalance, not a caloric one—specifically, the stimulation of insulin secretion caused by
>
> [Page: 10]{.highlight-ref}

> eating easily digestible, carbohydrate-rich foods: refined carbohydrates, including flour and cereal grains, starchy vegetables such as potatoes, and sugars, like sucrose (table sugar) and high-fructose corn syrup. These carbohydrates literally make us fat, and by driving us to accumulate fat, they make us hungrier and they make us sedentary.
>
> [Page: 10]{.highlight-ref}

> “What do I do to remain lean or lose the excess fat I have?” then this is it: stay away from carbohydrate-rich foods, and the sweeter the food or the easier it is to consume and digest—liquid carbohydrates like beer, fruit juices, and sodas are probably the worst—the more likely it is to make you fat and the more you should avoid it.
>
> [Page: 10]{.highlight-ref}

> being fat is associated with poverty, not prosperity—certainly in women, and often in men.
>
> [Page: 18]{.highlight-ref}

> If we’re not gluttons, then we must be guilty of sloth. If we’re not slothful, then gluttony is our sin.
>
> [Page: 29]{.highlight-ref}

> the coexistence of underweight and overweight in the same populations and even in the same families doesn’t pose a challenge to public-health programs; it poses a challenge to our beliefs about the cause of obesity and overweight.
>
> [Page: 31]{.highlight-ref}

> they enrolled nearly fifty thousand women in a trial, chose twenty thousand at random, and instructed them to eat a low-fat diet, rich in fruits, vegetables, and fiber.
>
> [Page: 33]{.highlight-ref}

> the women also decided, consciously or unconsciously, to eat less. According to the WHI researchers, the women, on average, consumed 360 calories a day less on their diets than they did when they first agreed to participate.
>
> [Page: 33]{.highlight-ref}

> After eight years of such undereating, these women lost an average of two pounds each. And their average waist circumference—a measure of abdominal fat—increased. This suggests that whatever weight these women lost, if they did, was not fat but lean tissue—muscle.\*
>
> [Page: 33]{.highlight-ref}

> Eating less—that is, undereating—simply doesn’t work for more than a few months, if that.
>
> [Page: 37]{.highlight-ref}

> The ubiquitous faith in the belief that the more calories we expend, the less we’ll weigh is based ultimately on one observation and one assumption. The observation is that people who are lean tend to be more physically active than those of us who aren’t.
>
> [Page: 46]{.highlight-ref}

> “I believe that you can reach the point,” Eco wrote, “where there is no longer any difference between developing the habit of pretending to believe and developing the habit of believing.”
>
> [Page: 53]{.highlight-ref}

> How is it possible that anyone stays lean, if all it takes to grow gradually obese is to overshoot this point of energy balance by twenty calories daily?
>
> [Page: 59]{.highlight-ref}

> One or two bites or swallows too many (out of the hundred or two we might take to consume a day’s worth of sustenance) and we’re doomed. If the difference between eating not too much and eating too much is less than a hundredth of the total amount of calories we consume, and that in turn has to be matched with our energy expenditure, to which we are, for the most part, completely in the dark, how can anyone possibly eat with such accuracy? To put it simply, the question we should be asking is not why some of us get fat, but how any of us avoids this fate.
>
> [Page: 59]{.highlight-ref}

> So either we live in a world where we rarely have enough food available or we consciously eat in moderation, which means pushing away from the table (or, for animals, walking away from the latest kill or cutting short a graze) before we’re satiated.
>
> [Page: 60]{.highlight-ref}

> The genes don’t determine how many calories these animals consume, but what they do with those calories.
>
> [Page: 68]{.highlight-ref}

> Newton’s laws of motion, Einstein’s relativity, the electrostatic laws, quantum mechanics—they all describe properties of the universe we no longer question. But they don’t tell us why we get fat. They say nothing about it, and this is true of the laws of thermodynamics as well.
>
> [Page: 73]{.highlight-ref}

> It is astounding how much bad science—and so bad advice, and a growing obesity problem—has been the result of the experts’ failure to understand this one simple fact.
>
> [Page: 73]{.highlight-ref}

> The way Wade explained it to me, the animal doesn’t get fat because it overeats, it overeats because it’s getting fat. The cause and effect are reversed. Both gluttony and sloth are effects of the drive to get fatter.
>
> [Page: 90]{.highlight-ref}

> The story of these ovariectomized rats reverses our perception of the cause and effect of obesity. It tells us that two behaviors—gluttony and sloth—that seem to be the reasons we get fat can in fact be the effects of getting fat.
>
> [Page: 92]{.highlight-ref}

> Anything that increases its mass, for whatever reason, will take in more energy than it expends. So, if a regulatory defect makes us both fatter and heavier, it is guaranteed to make us consume more calories (and so increase our appetite) and/or expend less than would be the case if this regulation was working perfectly.
>
> [Page: 97]{.highlight-ref}

> To paraphrase what the German internist Gustav von Bergmann said about this idea more than eighty years ago, we would never even consider the possibility that children grow taller because they eat too much and exercise too little (or that they stunt their growth by exercising too much). So why assume that these are valid explanations for growing fat (or remaining lean)?
>
> [Page: 99]{.highlight-ref}

> We don’t get fat because we overeat; we overeat because we’re getting fat.
>
> [Page: 99]{.highlight-ref}

> The message of eighty years of research on obese animals is simple and unconditional and worth restating: obesity does not come about because gluttony and sloth make it so; only a change in the regulation of the fat tissue makes a lean animal obese.
>
> [Page: 103]{.highlight-ref}

> Just as the animal research tells us that gluttony and sloth are side effects of a drive to accumulate body fat, it also says that eating in moderation and being physically active (literally, having the energy to exercise) are not evidence of moral rectitude. Rather, they’re the metabolic benefits of a body that’s programmed to remain lean.
>
> [Page: 104]{.highlight-ref}

> When we grow taller, it’s hormones and enzymes that are promoting our growth, and we consume more calories than we expend as a result. Growth is the cause—increased appetite and decreased energy expenditure (gluttony and sloth) are the effects. When we grow fatter, the same is true as well. We don’t get fat because we overeat; we overeat because we’re getting fat.
>
> [Page: 105]{.highlight-ref}

> Insulin plays many roles in the human body, but one critical role is to keep blood sugar under control.
>
> [Page: 114]{.highlight-ref}

> you secrete insulin primarily in response to the carbohydrates in your diet, and you do so primarily to keep blood sugar under control.† But the insulin also works simultaneously to orchestrate the storage and use of fat and protein. It makes sure, for instance, that your muscle cells get enough protein to do whatever rebuilding and repair is necessary, and it makes sure that you store enough fuel (glycogen and fat and protein as well) to function effectively between meals.
>
> [Page: 118]{.highlight-ref}

> Because the insulin level in the bloodstream is determined primarily by the carbohydrates that are consumed—their quantity and quality, as I’ll discuss—it’s those carbohydrates that ultimately determine how much fat we accumulate.
>
> [Page: 122]{.highlight-ref}

> if we want to get leaner—if we want to get fat out of our fat tissue and burn it—is to lower our insulin levels and to secrete less insulin to begin with.
>
> [Page: 124]{.highlight-ref}

> as we fatten, our energy demand increases, and our appetite will increase for this reason as well—particularly our appetite for carbohydrates, because this is the only nutrient our cells will burn for fuel when insulin is elevated. This is a vicious cycle, and it’s precisely what we’d like to avoid. If we’re predisposed to get fat, we’ll be driven to crave precisely those carbohydrate-rich foods that make us fat.
>
> [Page: 126]{.highlight-ref}

> The more insulin you secrete, the more likely it is that your cells and tissues will become resistant to that insulin. That means it will take more insulin to do the same glucose-disposal job, keeping blood sugar under control.
>
> [Page: 129]{.highlight-ref}

> even if you’re lean and active when you’re young, with your fuel-partitioning needle pointing toward fuel burning, your muscle cells are likely to become resistant to insulin as you get older. As they do, you’ll respond by secreting more insulin.
>
> [Page: 131]{.highlight-ref}

> the conventional wisdom that those of us who fatten as we move into middle age do so because our metabolism slows down, probably has this cause and effect backward. More likely is that our muscles become increasingly resistant to insulin, and this partitions more of the energy we consume into fat, leaving less available for the cells of muscles and organs to use for fuel.
>
> [Page: 131]{.highlight-ref}

> You don’t get fat because your metabolism slows; your metabolism slows because you’re getting fat.
>
> [Page: 131]{.highlight-ref}

> Not all of us get fat when we eat carbohydrates, but for those of us who do get fat, the carbohydrates are to blame; the fewer carbohydrates we eat, the leaner we will be.
>
> [Page: 134]{.highlight-ref}

> anything made of refined flour (bread, cereals, and pasta), liquid carbohydrates (beers, fruit juices, and sodas), and starches (potatoes, rice, and corn). These foods flood the bloodstream quickly with glucose. Blood sugar shoots up; insulin shoots up. We get fatter. Not surprisingly, these foods have been considered uniquely fattening for nearly two hundred years (as I’ll discuss later).\*
>
> [Page: 134]{.highlight-ref}

> The message of Adiposity 101 is simple enough: if you’re predisposed to get fat and want to be as lean as you can be without compromising your health, you have to restrict carbohydrates and so keep your blood sugar and insulin levels low.
>
> [Page: 140]{.highlight-ref}

> The foods that make us fat also make us crave precisely the foods that make us fat.
>
> [Page: 143]{.highlight-ref}

> What Adiposity 101 ultimately teaches us is that weight-loss regimens succeed when they get rid of the fattening carbohydrates in the diet; they fail when they don’t. What the regimen must do, in essence, is reregulate fat tissue so that it releases the calories it has accumulated to excess.
>
> [Page: 147]{.highlight-ref}

> The idea is that the longer a particular type of food has been part of the human diet, the more beneficial and less harmful it probably is—the better adapted we become to that food. And if some food is new to human diets, or new in large quantities, it’s likely that we haven’t yet had time to adapt, and so it’s doing us harm.
>
> [Page: 163]{.highlight-ref}

> our genes were effectively shaped by the two and a half million years during which our ancestors lived as hunters and gatherers prior to the introduction of agriculture twelve thousand years ago.
>
> [Page: 164]{.highlight-ref}

> It constitutes more than 99.5 percent of human history—more than a hundred thousand generations of humanity living as hunter-gatherers, compared with the six hundred succeeding generations of farmers or the ten generations that have lived in the industrial age.
>
> [Page: 164]{.highlight-ref}

> When averaged all together, these hunter-gatherer populations consumed about two-thirds of their total calories from animal foods and one-third from plants.
>
> [Page: 165]{.highlight-ref}

> Eat Western diets, get Western diseases—notably obesity, diabetes, heart disease, and cancer.
>
> [Page: 168]{.highlight-ref}

> So, if carbohydrates make us fat, which they do, and fat or saturated fat causes heart disease, which the authorities tell us they do, then we have a paradox: now the diet that naturally makes us leaner is also the diet that gives us heart disease. Getting leaner now increases our risk of heart disease, whereas it should do the opposite. This paradox suggests that only one of these two things can be true: either carbohydrates make us fat or dietary fat gives us heart disease but not both.
>
> [Page: 179]{.highlight-ref}

> That a particular fat in the diet raises LDL cholesterol, compared with, say, other fats or carbohydrates, does not mean it increases our risk of heart disease or is otherwise deleterious to our health. Another flaw in the logic concerns the implication of causality: the fact that the drugs known as statins lower LDL cholesterol and prevent heart disease does not necessarily imply that they prevent heart disease because they lower LDL.
>
> [Page: 186]{.highlight-ref}

> When you replace fat in your diet, even saturated fat, with carbohydrates, you lower your HDL, which means you make it more likely that you’ll have a heart attack, at least by this predictor of risk.
>
> [Page: 187]{.highlight-ref}

> the fear of fat—saturated, in particular—is based on the state of the science in the 1960s and 1970s, and it simply doesn’t hold up in the light of more recent research and the state of the science today.
>
> [Page: 195]{.highlight-ref}

> What metabolic syndrome tells us is that heart disease and diabetes are not caused by individual risk factors—low HDL, for instance, or high triglycerides, or small, dense LDL—but by insulin resistance and elevated levels of insulin and blood sugar playing havoc with cells everywhere.
>
> [Page: 196]{.highlight-ref}

> the fatter we are, the more likely we are to get cancer and the more likely we are to become demented as we age.
>
> [Page: 198]{.highlight-ref}

> “Carbohydrate withdrawal is often interpreted as a ‘need for carbohydrate,’ ” says Westman. “It’s like telling smokers who are trying to quit that their withdrawal symptoms are caused by a ‘need for cigarettes’ and then suggesting they go back to smoking to solve the problem.”)
>
> [Page: 215]{.highlight-ref}
