---
title: "2021: Personal Snapshot"
date: "01/31/2022"
description-meta: "An annual review of 2021. I took a look at what went well in 2021 and what I should change for 2022."
date-modified: last-modified
toc: true
toc-depth: 3
lightbox: true
fig-cap-location: margin
categories:
  - personal-snapshot
author:
  - name: Dylan Castillo
    url: https://dylancastillo.co
    affiliation: Iwana Labs
    affiliation-url: https://iwanalabs.com
citation: true
comments:
  utterances:
    repo: dylanjcastillo/blog_comments
    theme: dark-blue
---

When I see pictures from my childhood, I always try to remember _who I was_ at the time the photos were shot. Like, what was going through my mind? What motivated me? What scared me?

Remembering that is harder than it sounds. Pictures often help you recall sounds, smells, and emotions. But they don't work well if you're trying to recollect the inner workings of your mind.

There may not be a perfect way to remember how you felt at a certain period in your life. But I've found that reading things I've written in the past serves as a good substitute. After all, it's easier to find out what was on your mind from reading your journal than it is to do so from looking at a random photo of you and your cousins.

This blog is pretty recent, so I don't have much to refer to here. But when I was a teenager, I hung out in various online forums and wrote short stories and poems on text files. So if I want to remember Dylan from high school, I reread my posts, stories, and poems from that time.

Many of those online forums have since died, and I've lost most of those text files due to faulty backups. That got me thinking that I had to find a better way to store those _snapshots_ of myself.

So, for the foreseeable future, I've decided to write a _Personal Snapshot_ of the year in my blog at the end of each year. It's a yearly review that keeps a record of _who I was_ when I wrote it. I'm hoping to get a few laughs out of this in a decade.

If it's me rereading this, welcome back. This is Dylan from 2021.

## What Went Well?

Despite all the chaos due to COVID-19, I had a great year and achieved multiple goals I had set for myself.

First, I'm a freelancer now. In mid-2019, I began to consider this option. My first actions included adding random people on LinkedIn and informing them that I intended to work as a freelancer. That was as useless as it sounds!

This year, I took a more systematic approach. I focused on contacting recruiters and managers hiring contractors and was more persistent throughout the process. I even went after contracts that seemed out of reach, asked past colleagues for referrals, and asked to reconsider when I got "no" for an answer.

This change resulted in two freelancing contracts (European Commission and Deliveroo) and a teaching gig at [Nuclio](https://nuclio.school/?lang=en). It took a long time to get the first contract, but now I'm always getting new opportunities. Needless to say, I'm delighted.

To be honest, my day-to-day as a freelancer hasn't changed much compared to when I was a full-time employee. But that's expected, considering that I'm still selling my time rather than a product. I hope to change that soon.

Second, I'm earning more and saving more. I hadn't begun freelancing sooner because I didn't want to compete for 10$/h jobs on Upwork or Fiverr. I would only leave my full-time job if I could secure a freelancing contract that allowed me to save money at a similar or higher rate than I did as an employee.

This year, I negotiated good contracts, which increased my income and, as a result, my savings rate. All in all, I had three sources of revenue this year (in order of importance): Freelancing, cashing out a bit of crypto, and the teaching gig.

Third, a great relationship became a great team. This year my wife made a breakthrough in her career, which she had been fighting for over the last four years. It was tough, but we learned how to work together as a team in the process.

I became her part-time coach, cheerleader, and teammate throughout this time. I attempted to provide as much help as possible, as she studied 12 to 14 hours each day for about a year. We spent hours debating techniques, going over practice tests, and experimenting with slight tweaks to her prep system. It was well worth the effort!

It was one of those times when someone else accomplishes something, but you're so involved in the process that you feel like you've achieved it as well.

That got me thinking that good relationships are made of independent individuals who love and trust each other. But, just as important, is that they've decided to row in the same direction and work as a team to achieve their goals. That's how I see us.

Fourth, I took good care of my mental health. I've found that practicing Stoic precepts (such as daily journaling, negative visualization, and reminding myself that I cannot control most events in my life), and exercising regularly have made me happier. I still have bad days, but very few compared to previous years.

Fifth, it's been a good year for my family. My parents and sister are in good health, stay active, and have access to quality healthcare. Each family faces unique hurdles when they emigrate from Venezuela. Still, I'm pleased with how it's going for us thus far.

## What Should I Change?

For the last couple of years, life has been comfortable enough that I haven't needed to push my boundaries. That's no good.

First, I need to change my approach if I want to achieve financial freedom. I don't want to spend the next forty years of my life working for someone else five days per week while _enjoying freedom_ on weeknights and weekends. So I need to find a way to disentangle my income from my time, sooner rather than later.

Although freelancing was the first step in that direction, I am still selling my time. So next, I'd like to start selling a product, such as an ebook or a course. To do so, I need an audience willing to pay for it.

I studied people who've grown their online audiences quickly. With no exceptions, they did it by sharing high-quality content on social media on a regular basis. So I need to get off my butt and post regularly on social media.

Second, I must push myself out of my comfort zone. "What doesn't kill me makes me stronger," as Nietzsche famously said, should be complemented by the also valid "What keeps me cozy makes me weaker."

I feel that I've been too cozy the past few years, and I wasn't taking enough risks. If this keeps up, I'll be a boring old man with few stories to tell my grandchildren.

The problem is that society wants you to follow its _standard_ script when you reach adulthood: find a job, get married, have kids, get a mortgage, buy a car, have a couple of midlife crises, possibly get divorced, and then retire at 65 to tend to your garden.

That's not the life I want to live. Ask yourself, if that was a book, would you read it?

Most people wouldn't put a few hours to read such a book. They won't mind, though, spending their entire lives living that by that script.

One thing that a happy life and a good book have in common is that their foundation is a good story. Staying in your lane and following society's script is a certain way to write a story that no one wants to read, including yourself.

You're the hero of your own story. Heroes don't spend their lives binge-watching Netflix or scrolling through social media. They face challenges and grow as a result of that.

That's my goal for next year: grow by stepping out of my comfort zone.

What exactly will I be doing? You'll need to follow my blog to learn more 😉

## What do I Believe In?

Finally, I thought it'd be interesting to keep track of my beliefs, to see how they change over time. Some of these are mental frameworks, others are random thoughts.

Here's a non-exhaustive list of them:

- **Stoicism is the OG of mind hacks.** Cognitive Behavioral Therapy, the leading technique of psychotherapy, is [deeply influenced by Stoicism](https://medium.com/stoicism-philosophy-as-a-way-of-life/stoic-philosophy-as-a-cognitive-behavioral-therapy-597fbeba786a). My mental health has greatly improved as a result of following Stoic teachings. Others could benefit as well, so here are two good places to start: [Enchiridion](https://www.amazon.com/Enchiridion-Epictetus/dp/152156034X) or [A Guide to the Good Life](https://www.amazon.com/Guide-Good-Life-Ancient-Stoic/dp/0195374614).
- **Comfort kills.** At a micro-level, make your life _harder_, by doing things such as taking cold showers, fasting, and exercising every day. At a macro-level, do what scares you and excites you at the same time. When it comes to determining what will help you grow, trust your instincts.
- **Don't discuss nutrition and vaccines.** Add them to Religion, and Politics. Everyone has a very personal opinion on these topics. There's no point in discussing them with friends.
- **The 80/20 of Data Science.** Data Scientists like to build models, but most of the value comes from transforming raw data into useful insights for the business. That means setting up pipelines, generating reports, and building dashboards.
- **The 80/20 of staying healthy.** Avoid ultra-processed foods, sugar, and vegetable oils. Eat foods that have been around for a long time. Exercise regularly, doing Strength Training and some sort of cardio.

## Looking Ahead

I have high hopes for 2022. I'm eager to work on decoupling my income from my time and putting more time into my personal growth.

I hope to see you around!

_Thanks to María, Caryn, Christine, Georgia, and Mack for their feedback on this piece._
