---
title: "2024: Personal Snapshot"
date: "01/05/2024"
description-meta: "My annual review of 2024. I analyze what went well in 2024 and what I should change for 2025."
---

This is my annual review. I use it as a way to reflect on the past year and get a snapshot of "who I am" at the time of writing.

If it's me rereading this, welcome back. This is Dylan from 2024.

In previous snapshots, I listed what went well and what didn't. This year, I'm trying something new: a chronological approach. I feel 2024 went through three clear distinct phases.

## Early 2024

This was my "I'll do anything but build a consulting practice" phase.

In my last snapshot, I said that I was going to focus on building a consulting practice in 2024. Then I came up with a new product idea 😅 and spent the first two months of the year building a prototype.

[AItheneum^[yes, I know, what a terrible name.]](https://aitheneum.iwanalabs.com/) is a tool that helps you read classic philosophy books by making them easier to understand using AI. I pitched it as a way to make classic books more accessible to modern readers.

I had fun working on it, but it wasn't really solving anyone's problem. It was a vitamin, not a painkiller. By the time I released it, it was clear nobody cared about it (not even me!).

During this time, I was also half-assing talking to potential clients for freelance work and doing cold outreach to get clients. This had OK results, but I definitely didn't put enough effort into it.

This wasn't obvious at the time, but as I learned later, cold outreach at this stage of the game is a waste of time. When you're getting started, you should be asking for warm introductions or referrals. If you haven't built credibility yet, you're going to waste a lot of time trying to convince strangers to work with you.

On a brighter note, the highlight of this phase was doing sets at open mics almost every week. I had a lot of fun performing stand up, even though I bombed a few times. Every week I was looking forward to it.

But, eventually, I realized that it wasn't sustainable:

1. To get good at it, you have to make time for it. That means writing everyday, and performing as often as possible.
2. Open mics take a lot of time. To practice an 8 minute set, I'd often have to commute for 1 hour and stay for 1-2 hours of show (during which I did my 8 minutes).
3. As a beginner, you'll only get spots during weekday evenings. Which isn't great if you want to get enough sleep to be productive the next day.

Even so, I didn’t fully decide to quit until we had a health crisis at home. My wife and I weren’t prioritizing our health in the first months of the year, and it took its toll.

Stand up was fun, but it was distracting me from more important things. So I stopped.

I’d love to return to it in the future, once I have less pressing things to focus on.

## Mid 2024

This was the "work, learn, and build better habits" phase.

I worked with a couple of clients on AI projects, in the legal, construction, and CPG industries. Plus, I started writing blog posts again.

I often worked 12 hours days. I stopped going to the gym and switched to home workouts. I rarely went to social events.

This was intense. A few times, I felt very close to having a mental breakdown. I learned a lot about my own limits.

My biggest takeaway was that you can get a lot done if you deliberately choose to increase the intensity you put into things.

A highlight of this period was meeting some clients in person. Even though I’m a fan of remote work, getting everyone in the same room felt great. There's something about being in the same room that makes you more empathetic toward the people you're working with.

## Late 2024

This was the "What should I do in 2025?" phase.

The last months of the year were intense but less focused. I was still working with clients, but I also had more time to think about the future.

I did more sales during this time, and managed multiple projects in parallel. I also continued writing blog posts.

I traveled to Venezuela for the first time in 8 years, which was both wonderful and jarring. Once you get used to living in a developed country, it’s easy to forget how challenging daily life can be for so many people.

I also decided to read more academic research and refresh my [math skills](https://mathacademy.com/). The highlight of this phase was debunking a fairly popular post about the use of [Structured Ouputs in LLMs](https://dylancastillo.co/posts/say-what-you-mean-sometimes.html).

## Stats & photos

These are the stats for the year:

- 💻 Code: I committed code 322 days out of 365 (+16% from last year).
- 💰 Financials:
  - Highest revenue so far (+100% from last year).
  - 66% of my revenue comes from time-based billing (daily, hourly, etc.).
  - My biggest client represented 33% of my revenue.
- 📝 Sales:
  - I worked on 9 projects with 7 different clients.
  - I wrote 6 proposals.
  - I got 3 new clients.
- 💪 Exercise:
  - 112 strength training sessions (approx. 2.2 sessions per week)
  - 3,488 minutes of cardio (approx. 60 minutes per week)

You can see relevant photos from the year [here]().

## Lessons learned

Until this year, I thought that having a strong social media presence was key to getting more clients. But I was wrong.

I worked with 7 clients this year. They were either previous clients or referrals. I'm now a believer of the power of warm introductions. I still post on social media, but I no longer prioritize it. I believe there are higher leverage things I can do to get more clients.

I also learned that it's better to be too busy than too free. When you're busy, you learn a lot, you need to prioritize, and you end up becoming more creative as you often need to deliver under pressure.

Being "too busy" has taught me that I can do a lot more with less.

## What's next?

I've realized that I'm not a great predictor of what I want to do. I'm also not a great planner.

Right now, my biggest priority is to grow my consulting practice. I also have a painkiller product idea that I've been slowly building. I'm not putting much effort into it right now, but I believe it has potential.
