---
title: "2025: Personal Snapshot"
date: "2026-02-24"
date-modified: "2026-02-24"
draft: true
aliases:
  - /2025-personal-snapshot/
description-meta: "My annual review of 2025"
format:
  html:
    include-in-header:
      - text: |
          <link rel="stylesheet" href="/custom/gallery.css">
    include-after-body:
      - text: |
          <script defer src="/custom/gallery.js"></script>
categories:
  - personal-snapshot
---

This is my annual review. I use it as a way to reflect on the past year and get a snapshot of "who I am" at the time of writing.

If it's me rereading this, welcome back. This is Dylan from 2025.

In early 2024, I had hired a frontend developer to help me with some of my projects. The biggest isue was that I often had to walk him through the solution of the problem for him to implement it. The issue with this is that AI is already pretty good at that, so it didn't made a lot of sense to pay someone to essentially do the same work Claude Code does. 

I felt pretty bad about it, but also had to eventually be honest with myself about it. I pretty much did the opposite of how you should hire people: hire fast, fire slow.

Then, me and Maria moved to Cork, Ireland for three months. This went off to a rocky start. My wife and I had been having differences since the end of 2024, and moving to Ireland put this on steroids. We had some tough but necessary conversations. For some time now we had been living on autopilot, and had sometimes moving in different directions in what we wanted for the future. We also stopped being considaret with each other. 

Maria and me have been together for 15 years (8 years married). This, of course, means that we've been through lots of ups and downs during this time. Earlier this year was one of the few times where I felt we might not make it.

But we did, and we grew closer together. We both put the effort, and Ireland went from a terrible experience to one of the best experiences we've had as a couple. We traveled around the country, went for runs during sunset, tried every possible dairy product we could, and really became a team again. We now still cherish our time in Ireland, and even considered moving there! though I must say that we got lucky with weather! 

Then insomnia hit. It started a few weeks after I arrived to Ireland. It was a mix of stress and working from the same room where I was sleeping. But since then I've struggled with sleep. On good days it takes me 15-20 minutes to fall asleep. On bad days, it can take me 2-3 hours. I've been able to improve this over time, but I'm still not where I'd like to be.

On July, we moved to Salamanca, a small city to the north of Madrid. We moved here, because Maria got a good job opportunity and I can work from anywhere. We spent a good chunk of July and August moving. We went from a small and old 2-bedroom apartment, to a newly-renovated 4-bedroom apartment. It was a good change. Especially for me, given that I work from home. 

From August until December, I took part in challenging projects. This impacted my sleep and also caused me quite a bit of pain on my neck. I have some small protrusions that get worse when I don't sleep well or exercise. During the last 3 months of the year, this got as bad as it could have been. 

Some exciting projects have come up for this year. But I don't want to jinx it, so I won't talk about those until my next personal snapshot.
