---
title: "I hate AI side projects"
date: 2026-02-20
date-modified: 2026-02-20
categories:
    - essay
---

The best thing about AI is that EVERYONE can build now. The worst thing about AI is that EVERYONE can build now.

I've worked on and shared many of my [side projects](https://dylancastillo.co/projects.html) over the years. I built them because they gave me a chance to learn new things, such as [deploying my first web app on a VPS](https://github.com/dylanjcastillo/twitter-sentiment-tracker) or running [Python n the browser](https://github.com/dylanjcastillo/pandas-cheatsheet/). Sometimes, I got new clients when some of my [projects](https://seneca.dylancastillo.co/) went (just a bit) viral. And, more importantly, I had fun while building, like the time I [built a game](https://www.youtube.com/watch?v=FoiH8MjNQBI) (that the NYT didn't buy!), or when I replicated the results from a [1970s cognitive science experiment](https://task246.dylancastillo.co/).

I still work on side projects. But now I dread sharing them. The internet is saturated with AI slop. If you don't have something truly special, it can feel like you’re just adding one more padlock to those sagging, padlock-ridden bridges. Most of my past side projects would take me a few minutes or hours to build with Claude Code. Today, they're not worth talking about.

I rarely look at projects on Hacker News, Reddit, or X anymore. All landing pages and GitHub repos look the same. All launch messages look the same. The signal-to-noise ratio is unbearably low.

And, dear reader, don't get your hopes up. I'm also a sinner: I've contributed to the AI slop pile. I repent, but the damage is done. 

Still, I'm optimistic about AI, and I'm very appreciative of the impact it has had on my work. I don't want progress to stop or slow down. I just don't know yet how to properly engage with a world that's mostly created by AI.
